# 18대 제안자 칼럼 생성

- 발의자

In [1]:
import pandas as pd 
import numpy as np 
from ast import literal_eval
from tqdm import tqdm 
import numpy as np

In [2]:
gender = pd.read_csv('18th-gender-bill.csv', index_col=0, encoding='utf-8')
print(gender.shape)
gender.head(3)

(820, 14)

,의안번호,의안명,제안일자,제안자구분,의결일자,의결결과,제안회기,제안이유,소관위원회,제안자,발의자,제안정당,성별,여성의원 수
0,1814762,청소년 가출예방 및 자립지원에 관한 법률안,2012-05-25,의원,2012-05-29,임기만료폐기,제18대 (2008~2012) 제307회,"빈곤, 부모의 이혼, 가정폭력, 학대, 방임 및 학교부적응 등 복합적인 원인에...",여성가족위원회,"['강명순', '권영진', '권택기', '김무성', '김성태', '김소남', '김용...",강명순,새누리당,여성,5
1,1814751,저출산·고령사회기본법 일부개정법률안,2012-05-02,위원장,2012-05-02,원안가결,제18대 (2008~2012) 제307회,"위 9건의 법률안을 심사한 결과, 이들을 제304회 국회(임시회) 저출산고령화...",저출산고령화대책특별위원회,[],위원장,위원장,NaN,0
2,1814743,모자보건법 일부개정법률안,2012-05-02,위원장,2012-05-02,원안가결,제18대 (2008~2012) 제307회,"위 2건의 법률안을 심사한 결과, 제304회 국회(임시회) 제1차 전체회의(2...",보건복지위원회,[],위원장,위원장,NaN,0

In [3]:
gender = gender[['의안번호','제안자']]
gender.head(3)

      의안번호                                                제안자
0  1814762  ['강명순', '권영진', '권택기', '김무성', '김성태', '김소남', '김용...
1  1814751                                                 []
2  1814743                                                 []

In [4]:
%time gender['제안자'] = gender['제안자'].apply(literal_eval)

CPU times: user 24.7 ms, sys: 1.54 ms, total: 26.2 ms
Wall time: 25.8 ms

## 발의자 코딩

In [5]:
proposer_list = []

for names in gender['제안자']: 
    proposer_set = set(proposer_list)
    names_set = set(names)
    minus = list(names_set.difference(proposer_set))
    proposer_list.extend(minus)
    
len(proposer_list)

319

In [6]:
def get_proposer_dummies(proposer): 
    for n in tqdm(range(proposer.shape[1])): 
        df = pd.get_dummies(proposer[n])
        if n == 0: 
            final_df = df 
        else: 
            final_df = final_df.add(df, fill_value=0)
    return final_df

In [7]:
proposer = gender['제안자'].apply(lambda x: pd.Series(x))

%time proposer_dummies = get_proposer_dummies(proposer)
print(proposer_dummies.shape)

<ipython-input-7-5cd51fc5867d>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  proposer = gender['제안자'].apply(lambda x: pd.Series(x))
100%|██████████| 45/45 [00:45<00:00,  1.01s/it]

CPU times: user 44.1 s, sys: 515 ms, total: 44.6 s
Wall time: 45.6 s
(820, 319)

In [8]:
proposer_dummies.head(3)

,강기갑,강기정,강길부,강명순,강봉균,강석호,강성종,강성천,강승규,강용석,...,홍영표,홍일표,홍장표,홍재형,홍정욱,홍준표,홍희덕,황영철,황우여,황진하
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
gender = pd.concat([gender, proposer_dummies], axis=1)

In [10]:
gender = gender.drop(['제안자','의안번호'],1)

In [11]:
gender.head()

,강기갑,강기정,강길부,강명순,강봉균,강석호,강성종,강성천,강승규,강용석,...,홍영표,홍일표,홍장표,홍재형,홍정욱,홍준표,홍희덕,황영철,황우여,황진하
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
len(gender.columns)

319

In [13]:
gender.to_csv('18th-proposer-list.csv')

## 성별 평균 비교

### 여성

In [20]:
women_list = ['박근혜','김영선','전재희','나경원','진수희','전여옥','이혜훈',
             '박순자','박영아','정미경','강명순','배은희','이정선','김소남',
             '이은재','김금래','조윤선','손숙미','이애주','정옥임','김옥이',
             '이두아','최경희','이영애','이미경','추미애','조배숙','박영선',
             '신낙균','이성남','최영희','전혜숙','전현희','김상희','박선숙',
             '김유정','김진애','송영선','김을동','정영희','김혜성','김정',
             '이영애','박선영','곽정숙','이정희']
no_list_women = []

In [21]:
women = gender[women_list]
women.head()

,박근혜,김영선,전재희,나경원,진수희,전여옥,이혜훈,박순자,박영아,정미경,...,김진애,송영선,김을동,정영희,김혜성,김정,이영애,박선영,곽정숙,이정희
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0

In [22]:
add_list = [0 for n in range(len(no_list_women))]
print(add_list)
print(len(add_list))

[]
0

In [23]:
women_count = women.sum(axis=0).tolist() + add_list
print(len(women_count))

women_count = np.array(women_count)
print('평균 여성 발의:', np.mean(women_count))

46
평균 여성 발의: 41.80434782608695

### 남성

- 보궐선거, 재보궐선거 등 국회의원 수를 정확히 책정할 수 없음. 
- 따라서 당시 국회의원수를 기준으로 (국회의원수 - 여성의원수)로 책정함. 
- 동명이인 있어도 함께 세므로 평균을 내는 데에는 상관 없음.

In [24]:
men = gender.drop(women_list, 1)
men.head()

,강기갑,강기정,강길부,강봉균,강석호,강성종,강성천,강승규,강용석,강운태,...,홍영표,홍일표,홍장표,홍재형,홍정욱,홍준표,홍희덕,황영철,황우여,황진하
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
total_num = 299
total_men_num = total_num - len(women_list) - len(no_list_women)
print('총 남자의원 수:', total_men_num)

총 남자의원 수: 253

In [26]:
men_count = np.array(men.sum(axis=0).tolist())
np.sum(men_count)

7518.0

In [27]:
print('평균 남성발의:', np.sum(men_count) / total_men_num)

평균 남성발의: 29.715415019762847

## 정당 코딩

In [28]:
party = pd.read_csv('18th-gender-bill.csv', index_col=0, encoding='utf-8')
party.head()

,의안번호,의안명,제안일자,제안자구분,의결일자,의결결과,제안회기,제안이유,소관위원회,제안자,발의자,제안정당,성별,여성의원 수
0,1814762,청소년 가출예방 및 자립지원에 관한 법률안,2012-05-25,의원,2012-05-29,임기만료폐기,제18대 (2008~2012) 제307회,"빈곤, 부모의 이혼, 가정폭력, 학대, 방임 및 학교부적응 등 복합적인 원인에...",여성가족위원회,"['강명순', '권영진', '권택기', '김무성', '김성태', '김소남', '김용...",강명순,새누리당,여성,5
1,1814751,저출산·고령사회기본법 일부개정법률안,2012-05-02,위원장,2012-05-02,원안가결,제18대 (2008~2012) 제307회,"위 9건의 법률안을 심사한 결과, 이들을 제304회 국회(임시회) 저출산고령화...",저출산고령화대책특별위원회,[],위원장,위원장,NaN,0
2,1814743,모자보건법 일부개정법률안,2012-05-02,위원장,2012-05-02,원안가결,제18대 (2008~2012) 제307회,"위 2건의 법률안을 심사한 결과, 제304회 국회(임시회) 제1차 전체회의(2...",보건복지위원회,[],위원장,위원장,NaN,0
3,1814699,유아교육법 일부개정법률안,2012-02-27,위원장,2012-02-27,원안가결,제18대 (2008~2012) 제306회,"■ 대안의 제안경위가. 2009월 7월 7일 원희목의원 등 12인, 2009년 ...",교육과학기술위원회,[],위원장,위원장,NaN,0
4,1814659,보조생식에 관한 법률안,2012-02-10,의원,2012-05-29,임기만료폐기,제18대 (2008~2012) 제305회,■ 현재 난임으로 인한 보조생식 시술이 증가하고 있으나 보조생식에 관하여 「생...,보건복지위원회,"['이영애', '김정', '김혜성', '이두아', '이성남', '임영호', '정미경...",이영애,새누리당,여성,9

In [29]:
party['제안정당'].unique()

array(['새누리당', '위원장', '민주통합당', '정부', '자유선진당', '통합진보당', '무소속', '창조한국당',
       '국민생각'], dtype=object)

In [23]:
# party.loc[party['제안정당'] == '민주자유당', '제안정당'] = '신한국당'
# party.loc[party['제안정당'] == '민주당', '제안정당'] = '통합민주당'

In [30]:
conservative = ['창조한국당','새누리당','자유선진당','국민생각']
progressive = ['민주통합당','통합진보당']

party.loc[party['제안정당'].isin(conservative), '정당성향'] = '보수'
party.loc[party['제안정당'].isin(progressive), '정당성향'] = '진보'

In [31]:
party['정당성향'].unique()

array(['보수', nan, '진보'], dtype=object)

In [32]:
party['정당성향'].value_counts()

보수    412
진보    282
Name: 정당성향, dtype: int64

In [33]:
party.to_csv('18th-gender-bill-v3.csv', encoding='utf-8-sig')